// @ts-check

import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';

import {
  graphemeSegments,
  splitGraphemes,
  countGraphemes,
} from 'unicode-segmenter/grapheme';

// Real-world text fixtures generated by `scripts/corpora.js`.
//
// The official GraphemeBreakTest.txt covers only short synthetic
// sequences, and randomized property tests rarely produce patterns
// like conjunct-suppressing ZWNJ or cross-cluster state interactions.
// Natural corpora caught real bugs that both had missed.
// See https://github.com/cometkim/unicode-segmenter/issues/124
let corporaDir = new URL('./_corpora/', import.meta.url);

/**
 * @param {string} str
 * @return {string}
 */
let codepoints = str => [...str]
  .map(c => `U+${(/** @type {number} */ (c.codePointAt(0))).toString(16).toUpperCase().padStart(4, '0')}`)
  .join(' ');

/**
 * First-divergence report in the style of issue #124.
 *
 * @param {Array<{ segment: string, index: number }>} actual
 * @param {Array<{ segment: string, index: number }>} expected
 * @param {string} input
 * @param {number} at
 * @return {string}
 */
function formatDivergence(actual, expected, input, at) {
  let lo = Math.max(0, at - 2);
  let hi = at + 3;
  /** @param {Array<{ segment: string }>} segments */
  let chunks = segments => segments.slice(lo, hi).map(s => `[${s.segment}]`).join('');
  let anchor = expected[at] ?? actual[at];
  let last = expected[Math.min(hi, expected.length) - 1];
  let context = input.slice(expected[lo].index, last.index + last.segment.length);
  return [
    `diverges from Intl.Segmenter at segment #${at} (index ${anchor.index})`,
    `  codepoints:        ${codepoints(context)}`,
    `  intl:              ${chunks(expected)}`,
    `  unicode-segmenter: ${chunks(actual)}`,
  ].join('\n');
}

test('corpora', async t => {
  let intlSegmenter = new Intl.Segmenter();

  let files = (await readdir(corporaDir)).filter(name => name.endsWith('.txt')).sort();
  assert.ok(files.length > 0, 'no corpus fixtures found; run `node scripts/corpora.js`');

  for (let file of files) {
    await t.test(file, async () => {
      let text = await readFile(new URL(file, corporaDir), 'utf-8');
      // A truncated fixture would pass every check below vacuously.
      assert.ok(text.length > 2500, `${file} is suspiciously small (${text.length} chars)`);

      let expected = [...intlSegmenter.segment(text)];
      let actual = [...graphemeSegments(text)];

      let n = Math.min(actual.length, expected.length);
      for (let i = 0; i < n; i++) {
        if (actual[i].segment !== expected[i].segment || actual[i].index !== expected[i].index) {
          assert.fail(formatDivergence(actual, expected, text, i));
        }
      }
      if (actual.length !== expected.length) {
        assert.fail(formatDivergence(actual, expected, text, n));
      }

      // Bind the other public APIs to the same corpus.
      assert.equal(countGraphemes(text), expected.length);

      let split = [...splitGraphemes(text)];
      assert.equal(split.length, expected.length);
      for (let i = 0; i < split.length; i++) {
        if (split[i] !== expected[i].segment) {
          assert.fail(
            `splitGraphemes diverges from Intl.Segmenter at #${i}: `
            + `${codepoints(split[i])} != ${codepoints(expected[i].segment)}`,
          );
        }
      }
    });
  }
});
