#!/usr/bin/env node

// Copyright 2011-2015 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
// 
// This script has been modified from
// [https://github.com/unicode-rs/unicode-segmentation/blob/b4c9ce15/scripts/unicode.py]
// 
// Which is licensed under the
// [MIT license](../licenses/unicode-segmentation_MIT.txt)
// 
// This script uses the following Unicode tables:
// - DerivedCoreProperties.txt
// - auxiliary/GraphemeBreakProperty.txt
// - auxiliary/GraphemeBreakTest.txt
// - auxiliary/WordBreakProperty.txt
// - auxiliary/WordBreakTest.txt
// - ReadMe.txt
// - UnicodeData.txt

// @ts-check

/**
 * @import { WriteStream } from 'node:fs';
 * @import { UnicodeRange } from '#src/core.js';
 * 
 * @typedef {number[]} UnicodeValues
 *
 * @typedef {[from: number, to: number, categoryName: string]} CategorizedUnicodeRange
 */

import * as assert from 'node:assert/strict';
import * as path from 'node:path';
import { existsSync, createWriteStream } from 'node:fs';
import * as fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { encodeUnicodeData } from './lib/encoding.js';

let __dirname = path.dirname(fileURLToPath(import.meta.url));
let srcPath = path.resolve(__dirname, '../src');
let testPath = path.resolve(__dirname, '../test');
let dataPath = path.resolve(__dirname, 'unicode_data');

let preamble = `
// The following code was generated by "scripts/unicode.js",
// DO NOT EDIT DIRECTLY.
//
// @ts-check
`.trimStart();

/** @type {[major: number, minor: number, patch: number]} */
const UNICODE_VERSION = [17, 0, 0];
const UNICODE_VERSION_STRING = UNICODE_VERSION.join('.');

// these are the surrogate codepoints, which are not valid rust characters
/** @type {UnicodeRange} */
let surrogateCodepoints = [0xd800, 0xdfff, 0];

/** @type {Record<string, string[]>} */
let expandedCategories = {
  'Lu': ['LC', 'L'], 'Ll': ['LC', 'L'], 'Lt': ['LC', 'L'],
  'Lm': ['L'], 'Lo': ['L'],
  'Mn': ['M'], 'Mc': ['M'], 'Me': ['M'],
  'Nd': ['N'], 'Nl': ['N'], 'No': ['N'],
  'Pc': ['P'], 'Pd': ['P'], 'Ps': ['P'], 'Pe': ['P'],
  'Pi': ['P'], 'Pf': ['P'], 'Po': ['P'],
  'Sm': ['S'], 'Sc': ['S'], 'Sk': ['S'], 'So': ['S'],
  'Zs': ['Z'], 'Zl': ['Z'], 'Zp': ['Z'],
  'Cc': ['C'], 'Cf': ['C'], 'Cs': ['C'], 'Co': ['C'], 'Cn': ['C'],
};

/**
 * @param {string} f
 * @return {Promise<string>}
 */
let fetchData = async f => {
  let url = new URL(`https://www.unicode.org/Public/${UNICODE_VERSION_STRING}/ucd/${f}`);
  let filePath = path.join(dataPath, f);

  let content = null;
  if (existsSync(filePath)) {
    content = await fs.readFile(filePath, 'utf-8');
  } else {
    let res = await fetch(url);
    if (!res.ok) {
      throw new Error(`Failed to fetch ${url}`);
    }
    content = await res.text();
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, 'utf-8');
  }

  return content;
};

/**
 * @template T
 * @param {T[]} a 
 * @param {T[]} b 
 */
let arraysEqual = (a, b) => {
  return a.length === b.length && a.every((v, i) => v === b[i]);
};

/**
 * @param {number} from 
 * @param {number} to 
 * @return {Iterable<number>}
 */
let range = (from, to) => {
  return Array.from({ length: to - from }, (_, i) => i + from);
};

/**
 * @param {string} str 
 * @return {string}
 */
let capitalize = str => {
  return str[0].toUpperCase() + str.slice(1);
};

/**
 * @param {number} c 
 * @return {string}
 */
let escapeUnicode = c => {
  return `\\u{${c.toString(16).padStart(4, '0')}}`;
};

/**
 * @param {number} n
 * @return {boolean}
 */
let isSurrogate = n => {
  return surrogateCodepoints[0] <= n && n <= surrogateCodepoints[1];
};

/**
 * @param {UnicodeRange[]} ranges
 * @return {UnicodeValues}
 */
let ungroupCat = ranges => {
  /** @type {UnicodeValues} */
  let catOut = [];
  for (let [from, to] of ranges) {
    let cur = from;
    while (cur <= to) {
      catOut.push(cur);
      cur += 1;
    }
  }
  return catOut;
};

/**
 * @param {UnicodeValues} values
 * @return {UnicodeRange[]}
 */
let groupCat = values => {
  /** @type {UnicodeRange[]} */
  let catOut = [];
  let letters = [...new Set(values)].toSorted((a, b) => a - b);

  let curStart = letters.shift();
  assert.ok(curStart != null);

  let curEnd = curStart;
  for (let letter of letters) {
    assert.ok(letter > curEnd, `curEnd: ${curEnd}, letter: ${letter}`);

    if (letter === curEnd + 1) {
      curEnd = letter;
    } else {
      catOut.push([curStart, curEnd, 0]);
      curStart = curEnd = letter;
    }
  }
  catOut.push([curStart, curEnd, 0]);
  return catOut;
};

/**
 * @param {Record<string, UnicodeValues>} cats 
 * @return {Record<string, UnicodeRange[]>}
 */
let groupCats = cats => {
  /** @type {Record<string, UnicodeRange[]>} */
  let catsOut = {};
  for (let [cat, codes] of Object.entries(cats)) {
    catsOut[cat] = groupCat(codes);
  }
  return catsOut;
};

/**
 * @param {string} data
 * @return {Record<string, UnicodeRange[]>}
 */
let parseGencats = (data) => {
  /** @type {Record<string, UnicodeValues>} */
  let gencats = {};

  /** @type {Record<number, string[]>} */
  let udict = {};
  let rangeStart = -1;

  for (let line of data.split('\n')) {
    let data = line.split(';');
    if (data.length !== 15) {
      continue;
    }
    let cp = Number.parseInt(data[0], 16);
    if (isSurrogate(cp)) {
      continue;
    }
    if (rangeStart >= 0) {
      for (let i of range(rangeStart, cp)) {
        udict[i] = data;
      }
      rangeStart = -1;
    }
    if (data[1].endsWith(', First>')) {
      rangeStart = cp;
      continue;
    }
    udict[cp] = data;
  }

  for (let [code, data] of Object.entries(udict)) {
    let [codeOrg, name, gencat, combine, bidi,
      decomp, deci, digit, num, mirror,
      old, iso, upcase, lowcase, titlecase] = data;

    // place letter in categories as appropriate
    for (let cat of [gencat, 'Assigned'].concat(expandedCategories[gencat] || [])) {
      gencats[cat] ||= [];
      gencats[cat].push(Number.parseInt(code));
    }
  }

  return groupCats(gencats);
};

/**
 * @param {string} data 
 * @param {string[]} [interestingProps]
 * @return {Record<string, UnicodeRange[]>}
 */
let parseProperties = (data, interestingProps) => {
  let pattern = /^ *([0-9A-F]+)(?:\.\.([0-9A-F]+))? *; *(\w+)(?:; *(\w+))?/;

  /** @type {Record<string, UnicodeRange[]>} */
  let props = {};

  for (let line of data.split('\n')) {
    let match = line.match(pattern);
    if (!match) {
      continue;
    }

    let d_lo = match[1];
    let d_hi = match[2] || d_lo;
    let prop = match[3];
    let value = match[4];

    let propKey = value ? `${prop}=${value}` : prop;
    let propValue = value || prop;

    if (interestingProps && !interestingProps.some(p => propKey === p || prop === p)) {
      continue;
    }

    let lo = Number.parseInt(d_lo, 16);
    let hi = Number.parseInt(d_hi, 16);

    props[propValue] ||= [];
    props[propValue].push([lo, hi, 0]);
  }

  for (let [key, ranges] of Object.entries(props)) {
    props[key] = groupCat(ungroupCat(ranges));
  }

  return props;
};

/**
 * @param {string} data 
 * @param {string[]} [optsplit=[]]
 */
let parseTestData = (data, optsplit = []) => {
  /**
   * @param {string} str 
   * @param {UnicodeValues[]} chars 
   * @param {string[]} o
   * @return {[UnicodeValues[], string[]]}
   */
  let processSplitInfo = (str, chars, o) => {
    /** @type {UnicodeValues[]} */
    let outcs = [];
    /** @type {string[]} */
    let outis = [];
    let workcs = chars.shift();

    let s = str;

    // are we on a × or a ÷?
    let isX = false;
    if (s.startsWith('×')) {
      isX = true;
    }

    // find each instance of '(÷|×) [x.y] '
    while (s) {
      // find the currently considered rule number
      let sInd = s.indexOf('[') + 1;
      let eInd = s.indexOf(']');

      if (!isX || o.includes(s.substring(sInd, eInd))) {
        outis.push(s.substring(sInd, eInd));
        outcs.push(workcs || []);
        workcs = chars.shift();
      } else {
        workcs = workcs?.concat(chars.shift() || []);
      }

      let idx = 1;
      while (idx < s.length) {
        if (s.substring(idx).startsWith('×')) {
          isX = true;
          break;
        }
        if (s.substring(idx).startsWith('÷')) {
          isX = false;
          break;
        }
        idx += 1;
      }
      s = s.substring(idx);
    }

    outcs.push(workcs || []);
    return [outcs, outis];
  };

  /**
   * @param {string} str
   * @return {UnicodeValues[]}
   */
  let processSplitString = (str) => {
    /** @type {UnicodeValues[]} */
    let outls = [];

    /** @type {UnicodeValues} */
    let workls = [];

    let inls = str.split(' ');
    for (let i of inls) {
      if (i === '÷' || i === '×') {
        outls.push(workls);
        workls = [];
        continue;
      }

      let ival = Number.parseInt(`0x${i}`, 16);
      if (isSurrogate(ival)) {
        return [];
      }

      workls.push(ival);
    }

    if (workls.length) {
      outls.push(workls);
    }

    return outls;
  };

  let pattern = /^÷\s+([^\s].*[^\s])\s+÷\s+#\s+÷\s+\[0.2\].*?([÷×].*)\s+÷\s+\[0.3\]\s*$/;

  /**
   * @type {Array<[UnicodeValues[], string[]]>}
   */
  let testdata = [];
  for (let line of data.split('\n')) {
    // lines that include a test start with the ÷ character
    if (line.length < 2 || !line.startsWith('÷')) {
      continue;
    }

    let match = line.match(pattern);
    if (!match) {
      console.error(`error: no match on line where test was expected: ${line}`);
      continue;
    }

    // process the characters in this test case
    let chars = processSplitString(match[1]);
    // skip test case if it contains invalid characters (viz., surrogates)
    if (!chars.length) {
      continue;
    }

    let [proceedChars, info] = processSplitInfo(match[2], chars, optsplit);
    assert.equal(proceedChars.length - 1, info.length);

    testdata.push([proceedChars, info]);
  }

  return testdata;
};

/**
 * @template T
 * @param {WriteStream} f
 * @param {string} name
 * @param {T[]} table
 * @param {(row: T) => string} format
 */
let printTableRaw = (f, name, table, format) => {
  f.write(`export const ${name} = [\n`);
  for (let row of table) {
    f.write(`  ${format(row)},\n`);
  }
  f.write('];');
};

/**
 * @param {WriteStream} f
 * @param {CategorizedUnicodeRange[]} breakTable
 * @param {string[]} breakCats
 * @param {string} name
 * @param {string[]} [extraCats=[]] internal categories appended after the public ones
 * @returns
 */
let printBreakModule = (f, breakTable, breakCats, name, extraCats = []) => {
  let cats = ['Any', ...breakCats.toSorted()];
  let allCats = [...cats, ...extraCats];
  assert.ok(allCats.length <= 16, 'categories must fit in 4 bits');

  let capitalName = capitalize(name);
  let typeName = `${capitalName}Category`;
  let keyTypeName = `${typeName}Key`;
  let numTypeName = `${typeName}Num`;
  let rangeTypeName = `${typeName}Range`;

  f.write(preamble);
  f.write(`
/**
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
`,
  );
  /** @type {Record<string, number>} */
  let inversed = {};
  allCats.forEach((cat, idx) => {
    inversed[cat] = idx;
  });
  cats.forEach((cat, idx) => {
    f.write(` * @typedef {${idx}} ${typeName[0]}C_${cat}\n`);
  });

  f.write(' * @typedef {(\n');
  for (let cat of cats) {
    f.write(` *   | ${typeName[0]}C_${cat}\n`);
  }
  f.write(` * )} ${numTypeName}\n`);
  f.write(' */\n');

  f.write(`
/**
 * @typedef {import('./core.js').CategorizedUnicodeRange<${numTypeName}>} ${rangeTypeName}
 */
`,
  );

  f.write(`
/**
 * @typedef {(
`,
  );
  for (let cat of cats) {
    f.write(` *   | '${cat}'\n`);
  }
  f.write(` * )} ${keyTypeName}\n`);
  f.write(' */\n\n');

  f.write(`
/**
 * Grapheme category enum
 *
 * Note:
 *   The object isn't actually frozen
 *   because using \`Object.freeze\` increases 800 bytes on Brotli compression.
 *
 * @type {Readonly<Record<${keyTypeName}, ${numTypeName}>>}
 */
export const ${typeName} = {
`.trimStart(),
  );
  for (let cat of cats) {
    f.write(`  ${cat}: ${inversed[cat]},\n`);
  }
  f.write('};\n');

  let extraNote = extraCats.length
    ? `\n * Internal categories (never exposed through the public API):\n${extraCats.map(cat => ` *   - ${inversed[cat]}: ${cat}`).join('\n')}\n *`
    : ' *';
  f.write(`
/**
 * Encoded \`${capitalName}_Cluster_Break\` property ranges.
 *${extraNote}
 * @type {UnicodeDataEncoding}
 */
export const ${name}_data = /** @type {UnicodeDataEncoding} */ (
  '${encodeUnicodeData(breakTable.map(row => [row[0], row[1], 0]))}'
);

/**
 * Category of each range in {@link ${name}_data}, base36 digit per range.
 */
export const ${name}_cats = '${breakTable.map(row => inversed[row[2]].toString(36)).join('')}';
`,
  );
};

/**
 * UAX #29 pair-wise rules for extended grapheme cluster boundaries,
 * evaluated into a 16x16 decision table indexed by
 * `catBefore << 4 | catAfter`.
 *
 * - 0: boundary (GB999 and friends)
 * - 1: no boundary
 * - 2: GB12/GB13, no boundary iff odd run of RI precedes
 * - 3: GB11, no boundary iff the ZWJ was preceded by ExtPic Extend*
 * - 4: GB9c, no boundary iff InCB Consonant [Extend Linker]* Linker [Extend Linker]* precedes
 *
 * Category numbers follow the emitted `GraphemeCategory` enum:
 * 0 Any, 1 CR, 2 Control, 3 Extend, 4 Extended_Pictographic, 5 L, 6 LF,
 * 7 LV, 8 LVT, 9 Prepend, 10 Regional_Indicator, 11 SpacingMark, 12 T,
 * 13 V, 14 ZWJ, and the internal 15 InCB_Consonant.
 *
 * @see https://www.unicode.org/reports/tr29/tr29-45.html#Grapheme_Cluster_Boundary_Rules
 *
 * @return {string} 256 digits
 */
let buildGraphemePairTable = () => {
  let out = '';
  for (let b = 0; b < 16; b++) {
    for (let a = 0; a < 16; a++) {
      // InCB=Consonant (15) has the same GCB semantics as Any (0)
      let B = b === 15 ? 0 : b, A = a === 15 ? 0 : a, v = 0;
      if (B === 1) v = A === 6 ? 1 : 0;                                          // GB3: CR × LF, GB4: CR ÷
      else if (B === 2 || B === 6 || A === 1 || A === 2 || A === 6) v = 0;       // GB4: (Control | LF) ÷, GB5: ÷ (Control | CR | LF)
      else if (A === 3 || A === 14 || A === 11) v = 1;                           // GB9: × (Extend | ZWJ), GB9a: × SpacingMark
      else if (B === 9) v = 1;                                                   // GB9b: Prepend ×
      else if (B === 5) v = (A === 5 || A === 7 || A === 8 || A === 13) ? 1 : 0; // GB6: L × (L | V | LV | LVT)
      else if (B === 7 || B === 13) v = (A === 13 || A === 12) ? 1 : 0;          // GB7: (LV | V) × (V | T)
      else if (B === 8 || B === 12) v = A === 12 ? 1 : 0;                        // GB8: (LVT | T) × T
      else if (B === 14 && A === 4) v = 3;                                       // GB11: ExtPic Extend* ZWJ × ExtPic
      else if (B === 10 && A === 10) v = 2;                                      // GB12, GB13: RI × RI
      if (v === 0 && (B === 3 || B === 14) && a === 15) v = 4;                   // GB9c: InCB=C [E L]* L [E L]* × InCB=C
      out += v;
    }
  }
  return out;
};

/**
 * @param {WriteStream} f 
 */
let printIncbModule = async f => {
  let ucd = await fetchData('DerivedCoreProperties.txt');
  let props = parseProperties(ucd, ['InCB=Consonant']);
  let table = props['Consonant'];

  f.write(preamble);
  f.write(`
import { decodeUnicodeData } from './core.js';

/**
 * @typedef {import('./core.js').UnicodeRange} UnicodeRange
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
 * The Unicode \`Indic_Conjunct_Break=Consonant\` derived property table
 *
 * @type {UnicodeRange[]}
 */
export const consonant_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('${encodeUnicodeData(table)}')
);
`,
  );
};

/**
 * @param {WriteStream} f 
 */
let printGeneralModule = async f => {
  let [
    gencatSrc,
    derivedSrc,
  ] = await Promise.all([
    fetchData('UnicodeData.txt'),
    fetchData('DerivedCoreProperties.txt'),
  ]);

  let gencats = parseGencats(gencatSrc);
  let derived = parseProperties(derivedSrc, ['Alphabetic']);

  f.write(preamble);
  f.write(`
import { decodeUnicodeData } from './core.js';

/**
 * @typedef {import('./core.js').UnicodeRange} UnicodeRange
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
 * The Unicode \`L\` (Letter) properties data
 *
 * @type {UnicodeRange[]}
 */
export const letter_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('${encodeUnicodeData(gencats['L'])}')
);

/**
 * The Unicode \`N\` (Numeric) properties data
 *
 * @type {UnicodeRange[]}
 */
export const numeric_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('${encodeUnicodeData(gencats['N'])}')
);

/**
 * The Unicode \`Alphabetic\` properties data
 *
 * @type {UnicodeRange[]}
 */
export const alphabetic_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('${encodeUnicodeData(derived['Alphabetic'])}')
);
`,
  );
};

/**
 * @param {WriteStream} f 
 */
let printEmojiModule = async f => {
  let emojiData = await fetchData('emoji/emoji-data.txt');
  let emojiProps = parseProperties(emojiData, ['Extended_Pictographic', 'Emoji_Presentation']);

  f.write(preamble);
  f.write(`
import { decodeUnicodeData } from './core.js';

/**
 * @typedef {import('./core.js').UnicodeRange} UnicodeRange
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
 * The Unicode \`Emoji_Presentation\` properties data
 *
 * @type {UnicodeRange[]}
 */
export const emoji_presentation_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('${encodeUnicodeData(emojiProps['Emoji_Presentation'])}')
);

/**
 * The Unicode \`Extended_Pictographic\` properties data
 *
 * @type {UnicodeRange[]}
 */
export const extended_pictographic_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('${encodeUnicodeData(emojiProps['Extended_Pictographic'])}')
);
`,
  );
};

/**
 * @param {WriteStream} f 
 */
let printTestDataModule = async f => {
  f.write(preamble);
  f.write(`
/**
 * @typedef {[input: string, expected: string[]]} TestCase
 */
`,
  );

  /**
   * @typedef {[UnicodeValues, UnicodeValues[]]} TestCaseRow
   */

  /**
   * @param {TestCaseRow} row 
   * @return {string}
   */
  let formatTestCase = row => {
    let outstr = `['`;
    for (let c of row[0]) {
      outstr += escapeUnicode(c);
    }
    outstr += `', [`;
    let xfirst = true;
    for (let x of [row[1]]) {
      if (!xfirst) {
        outstr += '], [';
      }
      xfirst = false;
      let sfirst = true;
      for (let sp of x) {
        if (!sfirst) {
          outstr += ', ';
        }
        sfirst = false;
        outstr += `'`;
        for (let c of sp) {
          outstr += escapeUnicode(c);
        }
        outstr += `'`;
      }
    }
    outstr += ']]';
    return outstr;
  };

  let grapehmeTestDataSrc = await fetchData('auxiliary/GraphemeBreakTest.txt');
  // rules 9.1 and 9.2 are for extended graphemes only
  let optsplits = ['9.1', '9.2'];
  let graphemeTestData = parseTestData(grapehmeTestDataSrc, optsplits);

  /** @type {TestCaseRow[]} */
  let tests = [];

  for (let [c, i] of graphemeTestData) {
    let allChars = c.flatMap(s => s);

    /** @type {UnicodeValues[]} */
    let extgraphs = [];

    /** @type {UnicodeValues} */
    let extwork = [];

    extwork = extwork.concat(c[0]);
    for (let n of range(0, i.length)) {
      if (optsplits.includes(i[n])) {
        extwork = extwork.concat(c[n + 1]);
      } else {
        extgraphs.push(extwork);
        extwork = [];
        extwork = extwork.concat(c[n + 1]);
      }
    }

    // These are the extended grapheme clusters
    // And the JS' segmenter only cares extended grapheme clusters
    extgraphs.push(extwork);

    if (arraysEqual(extgraphs, c)) {
      tests.push([allChars, c]);
    } else {
      tests.push([allChars, extgraphs]);
    }
  }

  f.write(`
/**
 * Official Unicode test data for extended grapheme clusters
 *
 * @see http://www.unicode.org/Public/${UNICODE_VERSION_STRING}/ucd/auxiliary/GraphemeBreakTest.txt
 *
 * @type {TestCase[]}
 */
`,
  );
  printTableRaw(f, 'TESTDATA_GRAPHEME', tests, formatTestCase);
  f.write('\n');
};

/**
 * @param {string} file
 * @param {(f: WriteStream) => Promise<void>} print 
 */
let emitSrc = async (file, print) => {
  let filePath = path.join(srcPath, file);
  let writeStream = createWriteStream(filePath, 'utf-8');
  try {
    await print(writeStream);
  } finally {
    writeStream.end();
  }
};

/**
 * @param {string} file
 * @param {(f: WriteStream) => Promise<void>} print
 */
let emitTest = async (file, print) => {
  let filePath = path.join(testPath, file);
  let writeStream = createWriteStream(filePath, 'utf-8');
  try {
    await print(writeStream);
  } finally {
    writeStream.end();
  }
};


// Start main procedure

let [
  graphemeData,
  emojiData,
  // wordData,
  // sentenceData,
] = await Promise.all([
  fetchData('auxiliary/GraphemeBreakProperty.txt'),
  fetchData('emoji/emoji-data.txt'),
  // fetchData('auxiliary/WordBreakProperty.txt'),
  // fetchData('auxiliary/SentenceBreakProperty.txt'),
]);

let graphemeCats = parseProperties(graphemeData);
// Control
//  Note:
// This category also includes Cs (surrogate codepoints).
// We have to remove Cs from the Control category
graphemeCats['Control'] = groupCat(Array.from(
  new Set(ungroupCat(graphemeCats['Control'])).difference(
    new Set(ungroupCat([[surrogateCodepoints[0], surrogateCodepoints[1], 0]])),
  ),
));

let emojiProps = parseProperties(emojiData, ['Extended_Pictographic']);

// `InCB=Consonant` is folded into the grapheme table as an internal
// category so that the runtime can resolve GB9c without a second lookup.
// It never overlaps other GCB/ExtPic ranges as they all are `GCB=Any`.
let incbProps = parseProperties(
  await fetchData('DerivedCoreProperties.txt'),
  ['InCB=Consonant'],
);

/** @type {CategorizedUnicodeRange[]} */
let graphemeTable = [];
for (let [cat, ranges] of Object.entries(graphemeCats)) {
  for (let [from, to] of ranges) {
    graphemeTable.push([from, to, cat]);
  }
}
for (let [cat, ranges] of Object.entries(emojiProps)) {
  for (let [from, to] of ranges) {
    graphemeTable.push([from, to, cat]);
  }
}
for (let [from, to] of incbProps['Consonant']) {
  graphemeTable.push([from, to, 'InCB_Consonant']);
}
graphemeTable.sort((a, b) => a[0] - b[0]);

let last = -1;
for (let chars of graphemeTable) {
  if (chars[0] <= last) {
    throw new Error('Grapheme tables, Extended_Pictographic, and InCB=Consonant values overlap; need to store these separately!');
  }
  last = chars[1];
}

// let wordCats = parseProperties(wordData);
// /** @type {CategorizedUnicodeRange[]}  */
// let wordTable = [];
// for (let [cat, ranges] of Object.entries(wordCats)) {
//   for (let [from, to] of ranges) {
//     graphemeTable.push([from, to, cat]);
//   }
// }
// wordTable.sort((a, b) => a[0] - b[0]);

// let sentenceCats = parseProperties(sentenceData);
// /** @type {CategorizedUnicodeRange[]}  */
// let sentenceTable = [];
// for (let [cat, ranges] of Object.entries(sentenceCats)) {
//   for (let [from, to] of ranges) {
//     graphemeTable.push([from, to, cat]);
//   }
// }
// sentenceTable.sort((a, b) => a[0] - b[0]);

// Filter out ranges handled by inlined fast paths in cat()
let graphemeTableOptimized = graphemeTable.filter(([from, to, cat]) => {
  // CJK fast path: 0x3000-0x9FFF (inlined in cat())
  if (from >= 0x3000 && to <= 0x9FFF) {
    return false;
  }
  // Hangul syllables (LV/LVT): computed at runtime
  if (from >= 0xAC00 && to <= 0xD7A3 && (cat === 'LV' || cat === 'LVT')) {
    return false;
  }
  // Hangul Jamo Extended-B: 0xD7B0-0xD7FF (inlined in cat())
  if (from >= 0xD7B0 && to <= 0xD7FF) {
    return false;
  }
  // Private Use fast path: 0xE000-0xFDFF (inlined in cat())
  if (from >= 0xE000 && to < 0xFE00) {
    return false;
  }
  // Variation Selectors: 0xFE00-0xFE0F (inlined in cat())
  if (from >= 0xFE00 && to <= 0xFE0F) {
    return false;
  }
  // Tags and Variation Selectors Supplement: 0xE0000-0xE0FFF (inlined in cat())
  if (from >= 0xE0000 && to <= 0xE0FFF) {
    return false;
  }
  return true;
});

{
  // Verify the fast paths inlined in the runtime `cat()` against the raw table,
  // so a future Unicode update cannot silently break those assumptions.
  let catAt = (/** @type {number} */ cp) => {
    for (let [from, to, cat] of graphemeTable) {
      if (cp < from) break;
      if (cp <= to) return cat;
    }
    return 'Any';
  };
  /** @type {(cp: number) => string} */
  let inlined = cp => {
    // CJK: 0x3000-0x9FFF
    if (cp >= 0x3000 && cp < 0xA000) {
      if (cp < 0x3030) return cp >= 0x302A ? 'Extend' : 'Any';
      if (cp < 0x309B) {
        if (cp === 0x3030 || cp === 0x303D) return 'Extended_Pictographic';
        return cp >= 0x3099 ? 'Extend' : 'Any';
      }
      return (cp === 0x3297 || cp === 0x3299) ? 'Extended_Pictographic' : 'Any';
    }
    // Hangul syllables
    if (cp >= 0xAC00 && cp <= 0xD7A3) return (cp - 0xAC00) % 28 ? 'LVT' : 'LV';
    // Hangul Jamo Extended-B + surrogates as Any
    if (cp >= 0xD7A4 && cp < 0xE000) {
      if (cp <= 0xD7C6) return cp >= 0xD7B0 ? 'V' : 'Any';
      return (cp >= 0xD7CB && cp <= 0xD7FB) ? 'T' : 'Any';
    }
    // Private use
    if (cp >= 0xE000 && cp < 0xFE00) return cp === 0xFB1E ? 'Extend' : 'Any';
    // Variation selectors
    if (cp >= 0xFE00 && cp < 0xFE10) return 'Extend';
    // Tags and variation selectors supplement
    if (cp >= 0xE0000) {
      if (cp > 0xE0FFF) return 'Any';
      return ((cp >= 0xE0020 && cp < 0xE0080) || (cp >= 0xE0100 && cp < 0xE01F0))
        ? 'Extend'
        : 'Control';
    }
    throw new Error(`no inlined fast path covers ${cp.toString(16)}`);
  };
  for (let [lo, hi] of [
    [0x3000, 0x9FFF],
    [0xAC00, 0xFE0F],
    [0xE0000, 0xE1000],
  ]) {
    for (let cp = lo; cp <= hi; cp++) {
      assert.equal(
        inlined(cp),
        catAt(cp),
        `inlined fast path mismatches data at ${cp.toString(16)}`,
      );
    }
  }
  assert.ok(
    graphemeTable.every(([from]) => from <= 0xE0FFF),
    'cat() assumes no categorized ranges beyond 0xE0FFF',
  );
  // The runtime allocates fixed 320-entry buffers for the binary-search tail
  let tailCount = graphemeTableOptimized
    .filter(([from, to]) => to >= 0xFE10 && !(from >= 0x1F000 && to <= 0x1FAFF))
    .length;
  assert.ok(tailCount <= 320, `binary-search tail (${tailCount}) exceeds runtime buffer`);
}

await emitSrc(
  '_grapheme_data.js',
  async f => {
    printBreakModule(
      f,
      graphemeTableOptimized,
      Object.keys(graphemeCats).concat(['Extended_Pictographic']),
      'grapheme',
      ['InCB_Consonant'],
    );
    f.write(`
/**
 * UAX #29 pair-wise rules for extended grapheme cluster boundaries,
 * evaluated into a 16x16 decision table indexed by
 * \`catBefore << 4 | catAfter\`.
 *
 * - 0: boundary (GB999 and friends)
 * - 1: no boundary
 * - 2: GB12/GB13, no boundary iff odd run of RI precedes
 * - 3: GB11, no boundary iff the ZWJ was preceded by ExtPic Extend*
 * - 4: GB9c, no boundary iff InCB Consonant [Extend Linker]* Linker [Extend Linker]* precedes
 *
 * See \`buildGraphemePairTable\` in scripts/unicode.js for the rules.
 */
export const grapheme_pairs = '${buildGraphemePairTable()}';
`,
    );
  },
);

// emitSrc(
//   '_word_data.js',
//   async f => printBreakModule(
//     f,
//     wordTable,
//     Object.keys(wordCats),
//     'word',
//   ),
// );

// emitSrc(
//   '_sentence_data.js',
//   async f => printBreakModule(
//     f,
//     sentenceTable,
//     Object.keys(sentenceCats),
//     'sentence',
//   ),
// );

await emitSrc(
  '_incb_data.js',
  printIncbModule,
);

await emitSrc(
  '_general_data.js',
  printGeneralModule,
);

await emitSrc(
  '_emoji_data.js',
  printEmojiModule,
);

await emitTest(
  '_unicode_testdata.js',
  printTestDataModule,
);
