// The following code was generated by "scripts/unicode.js",
// DO NOT EDIT DIRECTLY.
//
// @ts-check

import { decodeUnicodeData } from './core.js';

/**
 * @typedef {import('./core.js').UnicodeRange} UnicodeRange
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
 * The Unicode `Emoji_Presentation` properties data
 *
 * @type {UnicodeRange[]}
 */
export const emoji_presentation_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('6xm,1,5p,3,3,,2,,eh,1,l,1,1e,b,17,,j,,d,,8,1,h,1,5,1,8,,5,,l,,7,1,1,,4,,2,,7,,4,1,s,,z,,1,,4,2,1,,1p,2,o,,e,,nv,1,1f,,4,,2hf2,,5m,,5a,,2,9,23,p,1,,o,,k,,2,4,1,2,l,1,4u,w,c,8,1,1x,1,l,c,16,4,4,c,g,3,,3,1y,1,,1,56,2,1q,d,3,1,n,i,,q,1,d,,2e,2c,1c,1x,6,,3,2,2,3,3,3,b,1,7,8,6b,b,4,,7v,1a,1,9,1,54,34,c,3,a,3,1k,1,,4,f,2,b,4,9')
);

/**
 * The Unicode `Extended_Pictographic` properties data
 *
 * @type {UnicodeRange[]}
 */
export const extended_pictographic_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('4p,,4,,68d,,c,,60,,m,,2i,5,f,1,a7,1,c,,4m,,p,a,4,2,5j,,6f,1,a,,9,,1m,3,1,4,9,,2,,2,1,2,,4,,2,,1,1,2,,3,,3,1,8,2,5,,1,,5,b,b,1,2,,1,1,1,,i,,2,1,i,5,1,,1,1,3,1,5,,2,1,4,1,b,1,5,1,2,,5,1,1,,1,1,k,1,5,5,1,3,2,,4,,2,,2,5,1,,2,,1,,1,,6,,3,,6,,a,1,f,,2,,4,,1,,4,2,1,,b,1,1c,2,9,,e,,e,,ac,1,cv,2,j,1,1f,,4,,yi,,c,,gp,,1,,2fze,,13,3,2s,b,f,1,f,,e,1,11,9,34,1,c,1,e,,2,9,j,1j,r,e,a,,k,,2,8,1,3,9,m,6,57,2,33,2,1,1,2,2,2a,2,2,1,3,5,71,1,1q,b,5,1,n,7,1,2,7,c,,2,3,2,,4,1,d,1,2,,8,1,9,,5,2,c,2,8,2,2,,1,,4,,6,,3,,6,2d,1c,1x,5,7,2,g,3,,1,5,2,c,62,11,c,3,1k,7,a,5,14,7,u,1,c,3,2,d,9,12,c,1a,1,9,1,54,2g,7,e,41,74,sd')
);
