// The following code was generated by "scripts/unicode.js",
// DO NOT EDIT DIRECTLY.
//
// @ts-check

import { decodeUnicodeData } from './core.js';

/**
 * @typedef {import('./core.js').UnicodeRange} UnicodeRange
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
 * The Unicode `Indic_Conjunct_Break=Consonant` derived property table
 *
 * @type {UnicodeRange[]}
 */
export const consonant_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('1sl,10,u,7,o,7,l,j,1,6,1,,3,3,y,1,1,,g,1,4j,j,1,6,1,1,1,4,1r,,r,j,1,6,1,1,1,4,y,1,1,,h,,4j,j,1,f,u,2,56,11,jp,16,k,,g,5,4,3,3,,3,1,7,2,4,c,c,,1dd,1f,h8,1g,52,1,6,w,h,7,1i,t,d,1,b,2,s0b,2,3,z,19,4,2,8,a,4,2p,f,1,2,6,,3,1,2o,a,5x,q,ilh,,f,3,1,2,1,s,1cd,z,t,,2,,fs,9,1,,2,,1,11,11m,6,2,,2,7,1,1,1,n,5s,,a,13,t,,b,13,w0,c,1,x')
);
