// The following code was generated by "scripts/unicode.js",
// DO NOT EDIT DIRECTLY.
//
// @ts-check

import { decodeUnicodeData } from './core.js';

/**
 * @typedef {import('./core.js').UnicodeRange} UnicodeRange
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
 * The Unicode `Indic_Conjunct_Break=Consonant` derived property table
 *
 * @type {UnicodeRange[]}
 */
export const consonant_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('10,1sl,7,1ug,7,1vc,j,1w5,6,1wq,,1wy,3,1x2,1,1y4,,1y7,1,1yo,j,239,6,23u,1,242,4,245,,261,j,26t,6,27e,1,27m,4,27p,1,28s,,28v,,29d,j,2dx,f,2ei,2,2fs,11,2l1')
);
