// The following code was generated by "scripts/unicode.js",
// DO NOT EDIT DIRECTLY.
//
// @ts-check

/**
 * The Unicode `Indic_Conjunct_Break=Consonant` derived property table
 *
 * @type {import('./core.js').UnicodeRange[]}
 */
export const consonant_table = JSON.parse('[[2325,2361],[2392,2399],[2424,2431],[2453,2472],[2474,2480],[2482,2482],[2486,2489],[2524,2525],[2527,2527],[2544,2545],[2709,2728],[2730,2736],[2738,2739],[2741,2745],[2809,2809],[2837,2856],[2858,2864],[2866,2867],[2869,2873],[2908,2909],[2911,2911],[2929,2929],[3093,3112],[3114,3129],[3160,3162],[3349,3386]]');
