// The following code was generated by "scripts/unicode.js",
// DO NOT EDIT DIRECTLY.
//
// @ts-check

/**
 * The Unicode `Indic_Conjunct_Break=Consonant` derived property table
 *
 * @type {import('./core.js').UnicodeRange[]}
 */
export const consonant_table = JSON.parse('[[2325,36],[2392,7],[2424,7],[2453,19],[2474,6],[2482,0],[2486,3],[2524,1],[2527,0],[2544,1],[2709,19],[2730,6],[2738,1],[2741,4],[2809,0],[2837,19],[2858,6],[2866,1],[2869,4],[2908,1],[2911,0],[2929,0],[3093,19],[3114,15],[3160,2],[3349,37]]');
