// The following code was generated by "scripts/unicode.js",
// DO NOT EDIT DIRECTLY.
//
// @ts-check

import { decodeUnicodeData } from './core.js';

/**
 * @typedef {import('./core.js').UnicodeRange} UnicodeRange
 * @typedef {import('./core.js').UnicodeDataEncoding} UnicodeDataEncoding
 */

/**
 * The Unicode `Indic_Conjunct_Break=Consonant` derived property table
 *
 * @type {UnicodeRange[]}
 */
export const consonant_ranges = decodeUnicodeData(
  /** @type {UnicodeDataEncoding} */
  ('26t,j,1y4,1,2dx,j,1w5,j,23u,6,28s,1,2fs,2,1ug,7,1wy,,1yo,1,245,4,27m,1,29d,,2ei,f,2l1,11,1sl,10,1vc,7,1wq,6,1x2,3,1y7,,239,j,242,1,261,,27e,6,27p,4,28v,')
);
