name: Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  integration:
    name: Check everything
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: |
          node \
            --test --test-reporter spec --test-reporter-destination=stdout \
            --experimental-test-coverage --test-reporter=lcov --test-reporter-destination=lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true

      - name: Build and publish to pkg.pr.new
        run: yarn pkg-pr-new publish
